DELIMITER $$
DROP TABLE IF EXISTS COMMENTRATING;
CREATE TABLE COMMENTRATING(
  custid int NOT NULL,
  prodid int NOT NULL,
  comment varchar(255),
  rating int,
  FOREIGN KEY(custid) REFERENCES CUSTOMER(id),
  FOREIGN KEY(prodid) REFERENCES PRODINFO(id)
);
DELIMITER ;
